### ISSUE TITLE
Error unpack requires string argument of length 4

### ISSUE THREAD

**Issue by priscila225** [AndroBugs/AndroBugs_Framework#1]
Hi,
The error occured when I was running the command line : 
AndroBugs_Framework-master$ **python androbugs.py -f /home/user/Test.apk**

This Error unpack requires string argument of length 4 appears, i think this is a zipfile.py issue (https://bugs.python.org/issue14315):
Folder:  ./tools/modified/androguard/patch/zipfile.py: 
**Python version: 2.7.3**

Also, i found a **workaround** for this error by unpacking and repacking the APK using zip/unzip on Ubuntu.

Error log:
*************************************************************************
**   AndroBugs Framework - Android App Security Vulnerability Scanner  **
**                            version: 1.0.0                           **
**     author: Yu-Cheng Lin (@AndroBugs, http://www.AndroBugs.com)     **
**               contact: androbugs.framework@gmail.com                **
*************************************************************************
Traceback (most recent call last):
  File "androbugs.py", line 3576, in main
    __analyze(writer, args)
  File "androbugs.py", line 1062, in __analyze
    a = apk.APK(apk_Path)
  File "/home/user/AndroBugs_Framework-master/tools/modified/androguard/core/bytecodes/apk.py", line 189, in __init__
    self.zip = zipfile.ZipFile(StringIO.StringIO(self.__raw), mode=mode)
  File "/usr/lib/python2.7/zipfile.py", line 714, in __init__
    self._GetContents()
  File "/usr/lib/python2.7/zipfile.py", line 748, in _GetContents
    self._RealGetContents()
  File "/usr/lib/python2.7/zipfile.py", line 807, in _RealGetContents
    x._decodeExtra()
  File "/usr/lib/python2.7/zipfile.py", line 373, in _decodeExtra
    tp, ln = unpack('<HH', extra[:4])
error: unpack requires a string argument of length 4

**Comment by AndroBugs** [comment]
It's a known issue. Less than 0.5% of the apps encounter this problem.

The root cause is in androguard decompiler. AndroBugs Framework just runs this code:
 - [androguard.core.bytecodes.apk.APK](https://github.com/androguard/androguard/blob/master/androguard/core/bytecodes/apk.py)("Test.apk")

**Comment by AlirezaChegini** [comment]
Python Bug, issue:
https://bugs.python.org/issue14315
