### ISSUE TITLE
HTTP errors when scanning my app after installing Firebase Cloud Messaging

### ISSUE THREAD

**Issue by psychicpuppy** [AndroBugs/AndroBugs_Framework#11]
Hello,

I get the following HTTP errors when scanning my APK after installing Google firebase Cloud Messaging support:

`[Critical] <SSL_Security> SSL Connection Checking:
           URLs that are NOT under SSL (Total:3):
               http://localhost
                   => Lcom/google/firebase/auth/api/model/VerifyAssertionRequest;-><init>(Ljava/lang/String; Ljava/lang/String;
                    Ljava/lang/String; Ljava/lang/String; Ljava/lang/String;)V
               http://plus.google.com/
                   => Lcom/google/android/gms/common/internal/zzp;-><clinit>()V
               http://www.google.com
                   => Lcom/google/android/gms/internal/zzjh$zza;-><init>(Landroid/content/Context;)V`

Is this something that Google is aware of?  I don't see these HTTP URL's when I run my app so I figure it must not be a issue.  What is your opinion?

**Comment by AndroBugs** [comment]
AndroBugs is a static analysis tool, which means code that is not executed may also be scanned by AndroBugs.
You should do dynamic analysis on your own after getting the results from AndroBugs to verify the issue. Not just simply take the results from AndroBugs Framework. If this is not an issue, you should just ignore it.
