### ISSUE TITLE
Pymongo library error 

### ISSUE THREAD

**Issue by DinaHkr** [AndroBugs/AndroBugs_Framework#13]
Hi 

I tried to store andro bugs result on MongoDB and it says py mongo library issue i tried to install all the library files and i could not able to store the data to database ..i have attached the screenshot here pls kindly give me the solution.
![capture](https://cloud.githubusercontent.com/assets/22589368/21475930/4413ba6e-cb58-11e6-87ef-cc360bb95f7e.JPG)

**Comment by AndroBugs** [comment]
The Windows executable version of AndroBugs Framework is compiled by "cxFreeze".
Comment out "https://github.com/AndroBugs/AndroBugs_Framework/blob/master/androbugs.py#L1047" and compile with cxFreeze on your own.
