### ISSUE TITLE
windows version, hash checksums not correct

### ISSUE THREAD

**Issue by filipesam** [AndroBugs/AndroBugs_Framework#17]
Hello, i've been using your tool, and it seems that the hash checksums that the tool does are not correctly computed.
From what i've seen it's only related with the windows .exe version.

I've tested with two linux utilities, "sha256sum" and with "openssl dgst -sha256 com.app.apk" to compare with the output of the tool.

thanks.

**Comment by AndroBugs** [comment]
The Windows version of AndroBugs is built with cxFreeze.
It is just for ease of use for Windows users.
Using the Linux version of AndroBugs is recommended.
