### ISSUE TITLE
ProGuard obfuscating - performance

### ISSUE THREAD

**Issue by Patryck95** [AndroBugs/AndroBugs_Framework#22]
Hi,
I've read the documentation about your tool and I have a question:
If I have an APK that has some of its code obfuscated by ProGuard, can your tool still make reverse engineering on it? And if it does what can I expect from its performance?

Thanks

**Comment by AndroBugs** [comment]
Absolutely!
ProGuard only changes the names of classes, functoins, variables... to make it unmeaningful.

What's the performance difference between the class name "aaa" and class name "bbb"?
