### ISSUE TITLE
Dead repository

### ISSUE THREAD

**Issue by noraj** [AndroBugs/AndroBugs_Framework#27]
For new people coming here this is a dead repository.

The author did a one shot initial commit and didn't merged any PR for 3 years.

Don't loose your time contributing.

**Comment by AndroBugs** [comment]
It means it has good quality.

**Comment by noraj** [comment]
Really? The README isn't even properly formated and there are at least 4 PR about updating it.
I really thought the project was dead.

Seeing this

![](https://i.imgur.com/K8O41Zi.png)

+ no comment on issues + unmerged PR for years nearly always mean it's a dead (born) project. 

But wow resurrection, nice to hear from #25 that the project will be updated in a few days. Happy come back :)
