### ISSUE TITLE
Error when going to upper level

### ISSUE THREAD

**Issue by javixeneize** [AndroBugs/AndroBugs_Framework#3]
Hi

I am trying to execute androbugs over an .apk i have in the upper folder, therefore i run androbugs sending as parameter -f ../name.apk

I have an error saying that filename should not contain slash or two dots

How can i make it work?

THanks

**Comment by AndroBugs** [comment]
It's a directory traversal security protection in AndroBugs Framework. Not a bug.
Make a directory under the same folder as androbugs.py
Put your APKs in that folder.
