### ISSUE TITLE
cert pinning critical vulnerability?

### ISSUE THREAD

**Issue by javixeneize** [AndroBugs/AndroBugs_Framework#4]
Hi

I am trying to do cert pinning in my app. I have this issue reported

[Critical] KeyStore Protection Checking:
The Keystores below seem using "byte array" or "hard-coded cert info" to do SSL pinning (Total: 1). Please manually check:
=> L/javi/cert;->a(Ljava/security/cert/X509Certificate;)Ljavax/net/ssl/SSLContext; (0x12) --->
Ljava/security/KeyStore;->load(Ljava/io/InputStream; [C)V

I am not using any byte array neither have the cert hardcoded. Any idea why this issue is reported?

Thanks

**Comment by AndroBugs** [comment]
Every security scanner has false positive.
Just ignore it if you don't think it is an issue.
